using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace SplineMesh {
    [ExecuteInEditMode]
    [DisallowMultipleComponent]
    [RequireComponent(typeof(Spline), typeof(ExtrudedHalfProfile), typeof(SplineScroll))]
    public class GrowingExtrusion : MonoBehaviour {
        private GameObject generated;
        private GameObject start;
        private GameObject end;

        private Spline spline;
        private SplineScroll splineScroll;
        private ExtrudedHalfProfile extrudedHalfProfile;

        public Material material;
        public float textureScale = 1;

        private void OnEnable() {
            string generatedName = "generated by " + GetType().Name;
            var generatedTranform = transform.Find(generatedName);
            generated = generatedTranform != null ?
                generatedTranform.gameObject :
                GetGenerated(generatedName);

            spline = GetComponentInParent<Spline>();
            splineScroll = GetComponent<SplineScroll>();
            extrudedHalfProfile = GetComponent<ExtrudedHalfProfile>();
        }

        private void Update() {
            GenerateMesh();
        }

        private void GenerateMesh() {
            UOUtility.DestroyChildren(generated);

            generated.GetComponent<MeshRenderer>().material = material;
            ExtrusionSegment mb = generated.GetComponent<ExtrusionSegment>();
            mb.ShapeVertices = extrudedHalfProfile.GetProfile();
            mb.TextureScale = textureScale;
            mb.SetInterval(spline, 0, spline.Length * splineScroll.rate);
        }

        private GameObject GetGenerated(string generatedName) {
            return UOUtility.Create(generatedName,
                    gameObject,
                    typeof(MeshFilter),
                    typeof(MeshRenderer),
                    typeof(ExtrusionSegment),
                    typeof(MeshCollider));
        }
    }
}
