using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace SplineMesh {
    [ExecuteInEditMode]
    [DisallowMultipleComponent]
    [RequireComponent(typeof(Spline), typeof(SplineScroll))]
    public class SpinningTool : MonoBehaviour {
        private GameObject generated;
        private GameObject tool;
        private Spline spline;
        private SplineScroll splineScroll;

        public GameObject toolPrefab;
        public float speed;

        private void OnEnable() {
            spline = GetComponentInParent<Spline>();
            splineScroll = GetComponentInParent<SplineScroll>();
            string generatedName = "generated by " + GetType().Name;
            var generatedTranform = transform.Find(generatedName);
            if(generatedTranform != null) {
                generated = generatedTranform.gameObject;
                tool = generated.transform.Find("tool").gameObject;
            } else {
                generated = UOUtility.Create(generatedName, gameObject);
                tool = Instantiate(toolPrefab);
                tool.name = "tool";
                tool.transform.parent = generated.transform;
                tool.transform.localPosition = Vector3.zero;
                tool.transform.localRotation = Quaternion.identity;
            }
        }

        private void Update() {
            if(tool != null) {
                tool.transform.Rotate(0, speed, 0);
            }
            var sample = spline.GetSampleAtDistance(spline.Length * splineScroll.rate);
            generated.transform.localPosition = sample.location;
            generated.transform.localRotation = sample.Rotation;
        }
    }
}
